coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        branches:
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
